services:
  ###> symfony/webapp ###
  webapp:
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV:-dev}
    container_name: webapp
    environment:
      APP_ENV: ${APP_ENV:-dev}
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
  ###< symfony/webapp ###

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB:-app}",
          "-U",
          "${POSTGRES_USER:-app}",
        ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: mailer
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

  ###> n8n ###
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "8001:5678"
    environment:
      GENERIC_TIMEZONE: "Europe/Paris"
      TZ: "Europe/Paris"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      WEBHOOK_URL: "https://ilian-igoudjil.decode.school"
      N8N_HOST: "ilian-igoudjil.decode.school"
      N8N_PORT: "5678"
      N8N_PROTOCOL: "https"
      N8N_SECURE_COOKIE: "false"
    volumes:
      - n8n_data:/home/node/.n8n
  ###< n8n ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
  ###> n8n ###
  n8n_data:
  ###< n8n ###

